project_id = "rkxqgdyqdffphysfwhdn"

[functions.analyze-review]
verify_jwt = false

[functions.analyze-company-keywords]
verify_jwt = false

[functions.notify-company-owner]
verify_jwt = false

[functions.notify-review-reply]
verify_jwt = false

[functions.generate-ai-recommendations]
verify_jwt = false
